### ISSUE TITLE
Investigate configurable conditional activation of MessagePopulators

### ISSUE THREAD

**Issue by petringo** [fmidev/aviation-message-archiver#90]
Sketch a proof-of-concept, whether it would be worth implementing properly a configuration option to activate configured `MessagePopulator` only when configured condition is satisfied. E.g.

```
- name: MyPopulator
  activateOn:
    productIdentifier:
      isOneOf:
        - product1
        - product2
  config:
    someOption: someValue
```

Implement properly if considered worth the effort, or abandon.
